### ISSUE TITLE
GPU and Time

### ISSUE THREAD

**Issue by kailugaji** [gimme1dollar/lift#1]
Thanks for your interesting work, can I ask what graphics card configuration you need to do these experiments and how long is the approximate wall clock time?

**Comment by jylee425** [comment]
Thanks! 

GPU: I used an Ubuntu server with 8 RTX3090 - probably consumed fewer GPUs. 
Wall clock time: The training took about around 15~20 hours.

**Comment by kailugaji** [comment]
> Thanks!
> 
> GPU: I used an Ubuntu server with 8 RTX3090 - probably consumed fewer GPUs. Wall clock time: The training took about around 15~20 hours.

Thank you for your reply.
